/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.drf.deep.space.sheep

import dev.drf.deep.space.sheep.core.Sheep

fun main() {
    println("dev.drf.deep.space.sheep.core.Sheep in the deep dark space...")
    val sheep = Sheep()
}
